[pyprland]
plugins = [
 "scratchpads",
]


[scratchpads.telegram]
animation = "fromRight"
command = "telegram-desktop"
class = "org.telegram.desktop"
size = "45% 75%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.slack]
animation = "fromRight"
command = "slack"
class = "Slack"
size = "45% 75%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "spotify"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
lazy = true

# todo:
# - ai chat
# - audio settings
