[pyprland]
plugins = [
 "scratchpads",
]


[scratchpads.telegram]
animation = "fromRight"
command = "telegram-desktop"
class = "org.telegram.desktop"
size = "45% 75%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.slack]
animation = "fromRight"
command = "slack"
class = "Slack"
size = "45% 75%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "spotify"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.pavucontrol]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "25% 35%"
max_size = "1920px 100%"
margin = 50
position = "22% 63%"
lazy = true

[scratchpads.easyeffects]
animation = "fromBottom"
command = "easyeffects"
class = "com.github.wwmm.easyeffects"
size = "25% 35%"
max_size = "1920px 100%"
margin = 50
position = "48% 63%"

# todo:
# - ai chat
